<!DOCTYPE html>
<html lang="en">
  <head>
    <title>cat door</title>
    <meta charset="utf-8">
    <style>
      body {
        margin: 0px;
        background-color: #999999;
        overflow: hidden;
      }

      #buttons {
        position: absolute;
        top:5px;
        left:5px;
      }
    </style>
    <script src="FileSaver.js"></script>
    <script src="three.min.js"></script>
    <script src="csg.js"></script>
    <script src="orbit_controls.js"></script>
    <script src="ThreeCSG.js"></script>
    <script src="cad.js"></script>
    <script src="../manifold/manifold.js"></script>
  </head>
  <body>
    <div id="buttons"></div>
    <script>

// All dimensions in millimeters
var PREPARE_FOR_PRINTING = false;
var CYLINDER_QUALITY = PREPARE_FOR_PRINTING ? 60 : 40;

var CUTOUT_WIDTH = 145;
var CUTOUT_HEIGHT = 156;
var CUTOUT_RADIUS = 26;
var FRAME_WIDTH = 7;
var DEPTH = 18;
var HINGE_DIAMETER = 9;
var HINGE_DEPTH = 6.2;
var MAGNET_HEIGHT = 10;
var MAGNET_WIDTH = 24;
var MAGNET_DEPTH = 7;
var MAGNET_EDGE = 2;

var WIDTH = CUTOUT_WIDTH/2 + FRAME_WIDTH;
var TOP = CUTOUT_HEIGHT/2 + FRAME_WIDTH;
var BOTTOM = -CUTOUT_HEIGHT/2 - 2*MAGNET_EDGE - MAGNET_HEIGHT;

var TAB_DEPTH = 14;
var TAB_HEIGHT = 40;
var TAB_WIDTH = FRAME_WIDTH + 20
var TAB_LOCK = 10;

var TOLERANCE = .6;

var NUMBER_FOUR_SCREW_RADIUS = 1.4;
var LOCK_SCREW_RADIUS = 1.6;

var M = manifold;

a3d.cad.init();
addGeometry();
a3d.cad.render();

function addGeometry() {
  var material = new THREE.MeshPhongMaterial( { color: 0xffffff } );
  var frameCSG = frame();

  var mesh = new THREE.Mesh(THREE.CSG.fromCSG(frameCSG), material );
  a3d.cad.addMesh(mesh, 'frame')

  var lockCSG = lock();

  var mesh = new THREE.Mesh(THREE.CSG.fromCSG(lockCSG), material );
  a3d.cad.addMesh(mesh, 'lock')
}

function lock() {
  // OUTER FRAME
  return CSG.cube({
      center: [CUTOUT_WIDTH/2 + TAB_WIDTH/2, 0, DEPTH],
      radius: [TAB_WIDTH/2, (TAB_HEIGHT-TOLERANCE)/2, TAB_DEPTH]
    })
    .union(CSG.cube({
      center: [(CUTOUT_WIDTH-TOLERANCE)/2 + FRAME_WIDTH/4, 0, DEPTH],
      radius: [(FRAME_WIDTH/2 - TOLERANCE)/2, (TAB_HEIGHT)/2+TAB_LOCK, TAB_DEPTH]
    }))
    .subtract(CSG.cylinder({
      start:[CUTOUT_WIDTH/2 + TAB_WIDTH/2,0,-1],
      end:[CUTOUT_WIDTH/2 + TAB_WIDTH/2,0,2*DEPTH+1],
      radius:LOCK_SCREW_RADIUS,
      slices: CYLINDER_QUALITY/4
    }));
}

function frame() {
  // OUTER FRAME
  return frameCSG()

    // INNER CUTOUT
    .subtract(cutoutCSG())

    // HINGE SOCKET
    .subtract(CSG.cylinder({
      start:[-WIDTH-1, CUTOUT_HEIGHT/2 - HINGE_DEPTH, DEPTH],
      end:[WIDTH+1, CUTOUT_HEIGHT/2 - HINGE_DEPTH, DEPTH],
      radius: HINGE_DIAMETER/2,
      slices: CYLINDER_QUALITY
    }))

    // MAGNET HOLDER
    .subtract(CSG.cube({
      center:[0, BOTTOM + MAGNET_EDGE + MAGNET_HEIGHT/2, DEPTH],
      radius:[MAGNET_WIDTH/2, MAGNET_HEIGHT/2, MAGNET_DEPTH/2]
    }))

    // SCREW HOLE
    .subtract(screwHoles())

    // TAB_CUTOUT
    .subtract(CSG.cube({
      center: [CUTOUT_WIDTH/2 + TAB_WIDTH/2, 0, DEPTH],
      radius: [TAB_WIDTH/2, TAB_HEIGHT/2, TAB_DEPTH]
    }))
    .subtract(CSG.cube({
      center: [CUTOUT_WIDTH/2 + FRAME_WIDTH/4, 0, DEPTH],
      radius: [FRAME_WIDTH/4, (TAB_HEIGHT)/2+TAB_LOCK, TAB_DEPTH]
    }))
    .subtract(CSG.cube({
      center: [-CUTOUT_WIDTH/2 - TAB_WIDTH/2, 0, DEPTH],
      radius: [TAB_WIDTH/2, TAB_HEIGHT/2, TAB_DEPTH]
    }))
    .subtract(CSG.cube({
      center: [-CUTOUT_WIDTH/2 - FRAME_WIDTH/4, 0, DEPTH],
      radius: [FRAME_WIDTH/4, (TAB_HEIGHT)/2+TAB_LOCK, TAB_DEPTH]
    }))
}

function screwHoles() {
  var margin = FRAME_WIDTH / 2;
  var left = -WIDTH + margin, right = WIDTH - margin;
  var top = TOP - margin, bottom = BOTTOM + margin;
  return [[top,left], [top,right], [bottom,left], [bottom,right]].reduce(function(m,p) {
    var hole = CSG.cylinder({
      start:[p[1],p[0],-1],
      end:[p[1],p[0],DEPTH+1],
      radius:NUMBER_FOUR_SCREW_RADIUS,
      slices: CYLINDER_QUALITY/4
    })
    return m ? m.union(hole) : hole;
  }, null)
}

function cutoutCSG() {
  var renderContext = M.CSGRenderer();

  M.step(2)
    ( M.vertexGenerator( function(step, vertexSink) {
        var z = -1 + step*DEPTH*2;
        M.Path([CUTOUT_WIDTH/2, CUTOUT_HEIGHT/2, z])
        .line([CUTOUT_WIDTH/2, -CUTOUT_HEIGHT/2 + CUTOUT_RADIUS, z])
        .arc([CUTOUT_WIDTH/2, -CUTOUT_HEIGHT/2, z], [CUTOUT_WIDTH/2 - CUTOUT_RADIUS, -CUTOUT_HEIGHT/2, z], CYLINDER_QUALITY)
        .line( [-CUTOUT_WIDTH/2+CUTOUT_RADIUS, -CUTOUT_HEIGHT/2, z])
        .arc([-CUTOUT_WIDTH/2, -CUTOUT_HEIGHT/2, z], [-CUTOUT_WIDTH/2, -CUTOUT_HEIGHT/2 + CUTOUT_RADIUS, z], CYLINDER_QUALITY)
        .line( [-CUTOUT_WIDTH/2, CUTOUT_HEIGHT/2, z])
        .vertices(2*CYLINDER_QUALITY, step)(vertexSink)
      } )
    ( M.facers( M.skin, M.closeEdge, M.capBottom, M.capTop )
    ( renderContext.renderer
  )));

  return renderContext.csgObject();
}

function frameCSG() {
  var renderContext = M.CSGRenderer();

  M.step(2)
    ( M.vertexGenerator( function(step, vertexSink) {
        var z = step*DEPTH;
        M.Path([-WIDTH, TOP, z])
        .line( [WIDTH, TOP, z])
        .line( [WIDTH, BOTTOM, z])
        .line( [-WIDTH, BOTTOM, z])
        .vertices(2*CYLINDER_QUALITY, step)(vertexSink)
      } )
    ( M.facers( M.skin, M.closeEdge, M.capBottom, M.capTop )
    ( renderContext.renderer
  )));

  return renderContext.csgObject();
}

function translateGeometry( g, x, y, z ) {
  matrix = new THREE.Matrix4().makeTranslation(x,y,z);
  g.applyMatrix(matrix);
}
function rotateGeometry( g, x, y, z ) {
  var matrix;
  if (x)
    matrix = new THREE.Matrix4().makeRotationX(x);
  if (y)
    matrix = (matrix||new THREE.Matrix4()).makeRotationY(y);
  if (z)
    matrix = (matrix||new THREE.Matrix4()).makeRotationZ(z);
  if (matrix)
    g.applyMatrix(matrix);
}

    </script>

  </body>
</html>
