<!DOCTYPE html>
<html lang="en">
  <head>
    <title>stablizer</title>
    <meta charset="utf-8">
    <style>
      body {
        margin: 0px;
        background-color: #999999;
        overflow: hidden;
      }

      #buttons {
        position: absolute;
        top:5px;
        left:5px;
      }
    </style>
    <script src="../FileSaver.js"></script>
    <script src="../three.min.js"></script>
    <script src="../csg.js"></script>
    <script src="../orbit_controls.js"></script>
    <script src="../ThreeCSG.js"></script>
    <script src="../cad.js"></script>
    <script src="../sylvester.js"></script>
    <script src="../../manifold/manifold.js"></script>
  </head>
  <body>
    <div id="buttons"></div>
    <script>

// All dimensions in millimeters
var PREPARE_FOR_PRINTING = true;
var CYLINDER_QUALITY = PREPARE_FOR_PRINTING ? 60 : 40;

var HINGE_DEPTH = 10;
var HINGE_RADIUS = 4;
var HINGE_FLANGE_RADIUS = 10;
var HINGE_FLANGE_DEPTH = 2;
var SCREW_HOLE_RADIUS = .8;

var HINGE_TOLERANCE = 1;
var ARM_LENGTH = 72;
var ARM_RADIUS = 10;
var ARM_HEIGHT = 8;
var ARM_DEPTH = 8;
var CORNER = 3;


var M = manifold;

a3d.cad.init();
addGeometry();
a3d.cad.render();

function addGeometry() {
  var material = new THREE.MeshPhongMaterial( { color: 0xffffff } );

  var hinge = hingeCSG();
  var mesh = new THREE.Mesh(THREE.CSG.fromCSG(hinge), material );
  a3d.cad.addMesh(mesh, 'hinge')

  var arm = armCSG();
  mesh = new THREE.Mesh(THREE.CSG.fromCSG(arm), material );
  a3d.cad.addMesh(mesh, 'arm')

  var tool = CSG.cube({
    center: [83/2, 20, 1],
    radius: [83/2, 1, 1]
  }).union(CSG.cube({
    center: [83, 20, 23/2],
    radius: [1, 1, 23/2]
  }));
  mesh = new THREE.Mesh(THREE.CSG.fromCSG(tool), material );
  a3d.cad.addMesh(mesh, 'tool')

}

function armCSG() {
  var theta = .25 * Math.PI;
  var axis = M.Path([0,0,ARM_DEPTH]).line([ARM_LENGTH,0,ARM_DEPTH])
    .arc([ARM_LENGTH + ARM_RADIUS,0,ARM_DEPTH],[ARM_LENGTH + ARM_RADIUS,0,ARM_RADIUS+ARM_DEPTH],CYLINDER_QUALITY/4)
    .arc([ARM_LENGTH + ARM_RADIUS,0,2*ARM_RADIUS+ARM_DEPTH],
        [ARM_LENGTH + ARM_RADIUS*Math.cos(theta),0,ARM_RADIUS*(1 + Math.sin(theta))+ARM_DEPTH],CYLINDER_QUALITY/4)
    .line([10*ARM_LENGTH/11,0,2.8*ARM_RADIUS+ARM_DEPTH])

  var profile = M.Path([0,-ARM_HEIGHT/2,-ARM_DEPTH])
    .line([0,-ARM_HEIGHT/2, -CORNER])
    .arc([0,-ARM_HEIGHT/2, 0], [0,-ARM_HEIGHT/2 + CORNER, 0], CYLINDER_QUALITY/4)
    .line([0,ARM_HEIGHT/2-CORNER, 0])
    .arc([0,ARM_HEIGHT/2, 0], [0,ARM_HEIGHT/2, -CORNER], CYLINDER_QUALITY/4)
    .line([0,ARM_HEIGHT/2, -ARM_DEPTH])
    .line([0,-ARM_HEIGHT/2, -ARM_DEPTH])

  var csg = M.CSGRenderer();
  var vertices = M.RibParameterizedPath( M.RibTransform([axis], 3+CYLINDER_QUALITY/2), extrudeAlong(axis, profile), 5+CYLINDER_QUALITY/2 );
  M.lift(vertices).generate( M.facers( M.skin, M.closeEdge, M.capTop, M.capBottom ) ).render(csg.renderer);
  var arm = csg.csgObject()
  if (PREPARE_FOR_PRINTING) {
    arm = arm.union(CSG.cylinder({
      start: [0, 0, 0],
      end: [0, 0, ARM_DEPTH],
      radius: HINGE_FLANGE_RADIUS,
      slices: CYLINDER_QUALITY / 2
    }))
    .subtract(CSG.cylinder({
      start: [0, 0, -1],
      end: [0, 0, HINGE_DEPTH + 1],
      radius: HINGE_RADIUS + HINGE_TOLERANCE/2,
      slices: CYLINDER_QUALITY
    }))
  }
  return arm;
}

function extrudeAlong(extrudePath, profile) {
  var initialTangent = vertToVec(extrudePath.tangentAt(0)).toUnitVector();
  var lastRotateAt = null;
  return function(vs) {
    var v = vs[0], vec = vertToVec(v);
    var currentTangent = vertToVec(extrudePath.tangentAt(v.ribStep)).toUnitVector();
    var cross = initialTangent.cross(currentTangent);
    var rotation = cross.distanceFrom($V([0,0,0])) *  Math.PI/2;
    var rotateAt = cross.toUnitVector();
    if (rotation == 0 && lastRotateAt)
      rotateAt = lastRotateAt;
    if (initialTangent.dot(currentTangent) < 0) rotation = Math.PI - rotation;
    if (rotation > Math.PI - .00000001) rotation = Math.PI - .000000001;
    lastRotateAt = rotateAt;
    function t(p) {
      var pv = $V(p);
      var rotated = rotation ? pv.rotate(rotation, $L([0,0,0], rotateAt)) : pv;
      return rotated.add(vec).elements;
    }
    return profile.transform(t);
  }
}

function hingeCSG() {
  return CSG.cylinder({
    start: [0, 0, 0],
    end: [0, 0, HINGE_DEPTH + HINGE_FLANGE_DEPTH],
    radius: HINGE_RADIUS,
    slices: CYLINDER_QUALITY
  })
  .union(CSG.cylinder({
    start: [0, 0, 0],
    end: [0, 0, HINGE_FLANGE_DEPTH],
    radius: HINGE_FLANGE_RADIUS,
    slices: CYLINDER_QUALITY
  }))
  .subtract(CSG.cylinder({
    start: [0, 0, -1],
    end: [0, 0, HINGE_DEPTH + HINGE_FLANGE_DEPTH + 1],
    radius: SCREW_HOLE_RADIUS,
    slices: CYLINDER_QUALITY
  }))

}

function screw(z) {
  return CSG.cylinder({
    start: [-NECK_WIDTH/2 - FLANGE_WIDTH + 1, 0, z],
    end: [-NECK_WIDTH/2 - FLANGE_WIDTH - BASE_WIDTH - 1, 0, z ],
    radius: NUMBER_FOUR_SCREW_RADIUS,
    slices: CYLINDER_QUALITY/4
  })
}

function profile(vs) {
  var v = vs[0];
  return M.Path([v.x, 0, FLANGE_DEPTH])
    .line([v.x, -FLANGE_HEIGHT/2, FLANGE_DEPTH])
    .line([v.x, -FLANGE_HEIGHT/2 - FLANGE_DEPTH, 2*FLANGE_DEPTH])
    .line([v.x, 0, 2*FLANGE_DEPTH])
    .line([v.x, 0, FLANGE_DEPTH])
}

function extrude(start, end, pathFunction, pathPoints) {
  var csg = M.CSGRenderer();
  var splines = [M.Path(start).line(end)];
  var vertices = M.RibParameterizedPath( M.RibTransform(splines, 2), pathFunction, pathPoints );
  M.lift(vertices).generate( M.facers( M.skin, M.closeEdge, M.capTop, M.capBottom ) ).render(csg.renderer);
  return csg.csgObject();
}

function vertToVec(v) { return $V([v[0],v[1],v[2]]); }

function translateGeometry( g, x, y, z ) {
  matrix = new THREE.Matrix4().makeTranslation(x,y,z);
  g.applyMatrix(matrix);
}
function rotateGeometry( g, x, y, z ) {
  var matrix;
  if (x)
    matrix = new THREE.Matrix4().makeRotationX(x);
  if (y)
    matrix = (matrix||new THREE.Matrix4()).makeRotationY(y);
  if (z)
    matrix = (matrix||new THREE.Matrix4()).makeRotationZ(z);
  if (matrix)
    g.applyMatrix(matrix);
}

    </script>

  </body>
</html>
