<!DOCTYPE html>
<html lang="en">
  <head>
    <title>stablizer</title>
    <meta charset="utf-8">
    <style>
      body {
        margin: 0px;
        background-color: #999999;
        overflow: hidden;
      }

      #buttons {
        position: absolute;
        top:5px;
        left:5px;
      }
    </style>
    <script src="../FileSaver.js"></script>
    <script src="../three.min.js"></script>
    <script src="../csg.js"></script>
    <script src="../orbit_controls.js"></script>
    <script src="../ThreeCSG.js"></script>
    <script src="../cad.js"></script>
    <script src="../../manifold/manifold.js"></script>
  </head>
  <body>
    <div id="buttons"></div>
    <script>

// All dimensions in millimeters
var PREPARE_FOR_PRINTING = true;
var CYLINDER_QUALITY = PREPARE_FOR_PRINTING ? 60 : 40;

var BASE_WIDTH = 8;
var FLANGE_DEPTH = 20;
var FLANGE_HEIGHT = 8;
var NUMBER_FOUR_SCREW_RADIUS = 1.4;
var SCREW_LENGTH = 26;
var SCREW_SEPARATION = 10;
var FLANGE_WIDTH = 2.5;
var NECK_WIDTH = 12.4;
var STABILIZER_HEIGHT = 12;
var STABILIZER_DEPTH = FLANGE_DEPTH + 12;

var SERVO_DEPTH = 40.5;
var SERVO_LENGTH = 24;
var SERVO_FLANGE_DEPTH = 9;
var SERVO_RADIUS = 25;
var INNER_RADIUS = 24;
var OUTER_RADIUS = 35;
var SERVO_X = -8.5;


var M = manifold;

a3d.cad.init();
addGeometry();
a3d.cad.render();

function addGeometry() {
  var material = new THREE.MeshPhongMaterial( { color: 0xffffff } );

  var stabilizer = CSG.cube({
    center: [-NECK_WIDTH/2 - FLANGE_WIDTH - BASE_WIDTH / 2, -STABILIZER_HEIGHT/2, FLANGE_DEPTH / 2],
    radius: [BASE_WIDTH/2, (STABILIZER_HEIGHT + FLANGE_HEIGHT)/2, FLANGE_DEPTH/2]
  })
  .union(CSG.cube({
    center: [0, -(STABILIZER_HEIGHT+FLANGE_HEIGHT)/2, STABILIZER_DEPTH/2],
    radius: [NECK_WIDTH/2+BASE_WIDTH, STABILIZER_HEIGHT/2, STABILIZER_DEPTH/2]
  }))
  .subtract(extrude([-NECK_WIDTH/2,0,0],[NECK_WIDTH/2,0,0], profile, 4))
  .subtract(screw(FLANGE_DEPTH/2 - SCREW_SEPARATION/2))
  .subtract(screw(FLANGE_DEPTH/2 + SCREW_SEPARATION/2))

  var mesh = new THREE.Mesh(THREE.CSG.fromCSG(stabilizer), material );
  a3d.cad.addMesh(mesh, 'stabilizer')
}

function screw(z) {
  return CSG.cylinder({
    start: [-NECK_WIDTH/2 - FLANGE_WIDTH + 1, 0, z],
    end: [-NECK_WIDTH/2 - FLANGE_WIDTH - BASE_WIDTH - 1, 0, z ],
    radius: NUMBER_FOUR_SCREW_RADIUS,
    slices: CYLINDER_QUALITY/4
  })
}

function profile(vs) {
  var v = vs[0];
  return M.Path([v.x, 0, FLANGE_DEPTH])
    .line([v.x, -FLANGE_HEIGHT/2, FLANGE_DEPTH])
    .line([v.x, -FLANGE_HEIGHT/2 - FLANGE_DEPTH, 2*FLANGE_DEPTH])
    .line([v.x, 0, 2*FLANGE_DEPTH])
    .line([v.x, 0, FLANGE_DEPTH])
}

function extrude(start, end, pathFunction, pathPoints) {
  var csg = M.CSGRenderer();
  var splines = [M.Path(start).line(end)];
  var vertices = M.RibParameterizedPath( M.RibTransform(splines, 2), pathFunction, pathPoints );
  M.lift(vertices).generate( M.facers( M.skin, M.closeEdge, M.capTop, M.capBottom ) ).render(csg.renderer);
  return csg.csgObject();
}


function translateGeometry( g, x, y, z ) {
  matrix = new THREE.Matrix4().makeTranslation(x,y,z);
  g.applyMatrix(matrix);
}
function rotateGeometry( g, x, y, z ) {
  var matrix;
  if (x)
    matrix = new THREE.Matrix4().makeRotationX(x);
  if (y)
    matrix = (matrix||new THREE.Matrix4()).makeRotationY(y);
  if (z)
    matrix = (matrix||new THREE.Matrix4()).makeRotationZ(z);
  if (matrix)
    g.applyMatrix(matrix);
}

    </script>

  </body>
</html>
